#!/Users/shubham/projects/guitar_tracker/backend/spotify-downloader/.venv/bin/python
# -*- coding: utf-8 -*-
import sys
from spotdl import console_entry_point
if __name__ == "__main__":
    if sys.argv[0].endswith("-script.pyw"):
        sys.argv[0] = sys.argv[0][:-11]
    elif sys.argv[0].endswith(".exe"):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(console_entry_point())
